### ISSUE TITLE
Crit and SP values for mages

### ISSUE THREAD

**Issue by ForgeGit** [BreakBB/ExtendedCharacterStats#138]
## Bug description

There are 2 bugs I would like to report:

1. For mages with the talent "Mind Mastery", the spell power values in ECS are consistently 5% higher than what it is shown in the default character stats (DCS?). Looking at the code it seems like there is a multiplier hardcoded for "Arcane Instability", using the following:
"GetTalentInfo(1, 15)"
However, I think the 15th talent from left to bottom in the arcane tab for mages is "Mind Mastery" and NOT "Arcane Instability", leading to ECS to show the SP values as 5% higher.

2. When using the Molten Armor buff, ECS is not adding up the increased 3% spell crit obtained from the buff, however, DCS does consider it leading to a 3% difference in crit

## Screenshots
Bug 1
![image](https://user-images.githubusercontent.com/75605537/123831760-42c2fb00-d8ca-11eb-8997-6ed843848cfc.png)

Bug 2
![image](https://user-images.githubusercontent.com/75605537/123832072-95041c00-d8ca-11eb-91fa-1e5ec62caae6.png)

**Comment by BreakBB** [comment]
Hey @ForgeGit thanks for this detailed report!

For the first part: Yes, you are absolutely right! The position of the Arcance Instability talent moved with the change from Classic to TBC. Will be easy to fix 👍🏻 

For the second issue, I would be very glad if you could help me, since I don't have a mage yet with Molten Armor. Could you run the following command with just the Molten Armor buff on yourself and share a screenshot of the output?

`/dump UnitAura("player", 1, "HELPFUL")`

**Comment by ForgeGit** [comment]
Hey! Sorry for the delay. Good to hear you might be able to work it out in the beta server :)

Just in case I am attaching the output screenshot regardless:

![image](https://user-images.githubusercontent.com/75605537/124063393-5f5d5100-d9f8-11eb-8217-34b6af8438b1.png)

**Comment by ForgeGit** [comment]
Hi! I do have another quick question regarding stat values for mages:

Is the hit % values currently adding +3% hit for those with the "Elemental Precision" talent? 

It would seem like that is the case, and I think that is innacurate for those running arcane spec as mages.
Currently those specced as arcane are using "Arcane Focus" which gives 10% hit to arcane spells. On top of that, it is now proven that "Elemental Precision" gives 3% hit to frostbolt, so in summary, it would be innacurate to assume "Elemental precision" gives 3% hit to all spell talents, since it would only be 3% for frost and fire (possibly only fire, since then again, it would be 6% for frostbolt).

**Comment by BreakBB** [comment]
@ForgeGit Yes, the Elemental Precision talent is taken into account for all Mage spells which I know is wrong now. In Classic it was save to assume since there weren't any relevant Arcane spells.

I have yet to find a way to fix this since ECS doesn't show spell hit split by spell school.

Another thing: I can't find an issue with Molten Armor. It gives my Mage a proper 3% Spell Crit bonus.

**Comment by cliaz** [comment]
> it is now proven that "Elemental Precision" gives 3% hit to frostbolt

I'm not sure if this is relevant or not (due to your comment about ECS not showing spell hit per school), but the Elemental Precision does actually give 6% hit to binary frost spells. The tooltip is wrong, and the mage discord has continued to support that.

An arcane mage running the traditional 40/0/21 spec, with 5 points in Arcane Focus and 3 points in Elemental Precision, would have the following talent-driven bonuses to hit:

- Arcane: +10%
- Fire: +3%
- Frost: +6%

**Comment by BreakBB** [comment]
Hey @cliaz that is interesting 😮 But as you already guessed "right now" it is not really relevant for ECS since it doesn't show hit per school. Might be worth to implement though, but I am very limited in time 🙈
