### ISSUE TITLE
Hit Chance for Balance Druids isnt calculated properly

### ISSUE THREAD

**Issue by Qidpuncher-outland** [BreakBB/ExtendedCharacterStats#210]
ExtendedCharacterStats-v3.0.3

the shown hitchance in balance spec seems to be 3% over the actual value (with Improved Faerie Fire for its 3% and Balance of Power for 4% included)
Version: TBC-Classic (WotLK Prepatch)
Example: 8,4% from items + (potentialy) 7% from talents -> should be 15.4% not the displayed 18.4%

https://tbc.wowhead.com/spell=33592/balance-of-power
https://tbc.wowhead.com/spell=33602/improved-faerie-fire

**Comment by Qidpuncher-outland** [comment]
![unknown](https://user-images.githubusercontent.com/105646248/191353734-06f91da1-75d6-4686-9926-039b3e056812.png)

**Comment by BreakBB** [comment]
Hey @Qidpuncher-outland great finding. Actually ECS is 6% over the actual value as it currently checks the "Wrath of Cenarius" talent instead of "Balance of Power". When changing to Wotlk (pre patch) all talent trees got mixed up and only a few talents are checked correctly. So ECS got 10% from the talents what should have been 4%.

IFF is not taken into the hit rating, so you have to add the other hit modifies (if on the specific mob/boss).

Will fix and release this shortly!
