### ISSUE TITLE
classic mana regen formula is wrong

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [BreakBB/ExtendedCharacterStats#231]
## Bug description
Mana regen from spirit formula shown here https://github.com/BreakBB/ExtendedCharacterStats/blob/bf2ba28de92a984c78af0b79bae5fc08554d8ffa/Modules/Data/MP5.lua#L93 is wrong for classic.

It should be `(12.5 + spirit/4)/2` mana every second while not casting for more than 5s
and
`spirit_casting_modifier*(12.5 + spirit/4)/2` mana every second otherwise

`12.5` is a constant valid for mages
`spirit_casting_modifier` takes into account mage armour and other stuff like that

## Version
WoW Classic

**Comment by BreakBB** [comment]
Hey @Alessandro-Barbieri thanks for reporting this. Looks like something slipped when moving to Wotlk.

The thing with MP5 in ECS is, that we split certain constrains. So you get "MP5 from Buffs", "MP5 while casting", "MP5 while not casting" and "MP5 from Spirit".

Did you verify the changes you suppose are true from "MP5 from Spirit"? Because this value should not differ combat or not. `spirit_casting_modifier` is also already included in "MP5 while casting".

**Comment by Neischa** [comment]
I can add to this - I have 128 regen in total while not casting and with mage armor (30% of it allowed when casting) it say I have 11.53 mp5 which is clearly wrong, actually it is 40 mp5 or 16 mp2. Also mp5 from spirit seems to be off as if I for example switch spirit item for non spirit item, it changes mp5 (not casting) by 5.63, while the mp5 (spirit) only by 3.65. It should be same if the only thing I am doing is adding/removing spirit.

Or do I understand these stats wrong?
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/103169596/91ae682a-ce11-4e61-b35c-65733e0706c4)

**Comment by BreakBB** [comment]
I am closing this in favor of #318 to fix multiple issues in one go.
