### ISSUE TITLE
In SOD spell hit is incorrect

### ISSUE THREAD

**Issue by vidorgyozo** [BreakBB/ExtendedCharacterStats#325]
## Bug description
In SOD it seems that the attack and spell hit chance is not counted for spell hit in ECS.

## Screenshots
As you can see I have spell and attack hit items, and you can see they count for ranged hit (top) but not for spell hit (bottom).
![image](https://github.com/user-attachments/assets/d6571d36-3520-4cb0-8902-4797ae02b459)

## Version
Latest update for SOD right now, updated on 7/10/2024 from Curseforge.

**Comment by retrobloodfang** [comment]
Spell hit on Classic Era is also incorrect. My character shows 7% spell hit even though my mage talents and gear together should be 14% hit

**Comment by BreakBB** [comment]
I actually need to add the new SoD ring runes, which provide hit.

Other than that I am not aware of an actual issue.

But I do know about #173 which is kind of an issue, because "Spell Hit" is not detailed enough for talents which provide "Hit on Frost spells" or "Hit on Afflication spells".

@vidorgyozo can you provide an example item for "As you can see I have spell and attack hit items"? I don't understand what you mean by that 🤔
