### ISSUE TITLE
Total Spell hit on Classic Era calculated incorrectly #326

### ISSUE THREAD

**Issue by retrobloodfang** [BreakBB/ExtendedCharacterStats#328]
## Bug description
I was looking for a friend's Warlock character and ECS displays 14% hit which is not correct. The hit % gained off his gear is 12%, plus the hit off of the hit % talent in the Affliction tree. But Warlock spell hit % scales differently.  One point into 'Suppression' is [effectively +2% spell hit](https://www.bluetracker.gg/wow/topic/eu-en/1015913266-chance-to-hit-with-spells-spell-hit-rating/#:~:text=Chance%20to%20hit%20with%20spells%20can%20be%20increased%20by%20talents,of%2010%25%20(5pts).) (for affliction spells only though so it's not general spell hit - shadow bolt hit will remain the same)

What I think is happening here is that ECS counts 2% hit from the Affliction 'Suppression' talent being 2/5. However Affliction wise the caster should be hit capped because 12% hit from items and 4% hit from 2/5 talens. If it was 5/5, ECS would've said 12 + 5 = 17% (I think).
![image](https://github.com/user-attachments/assets/69d62d46-45b6-4e7b-bb51-fdc59a334cb7)

## Screenshots
![image](https://github.com/user-attachments/assets/a737f36d-bb0b-4486-8077-d585ad66b38a)

As you can see the gear hit is 12%, I have confirmed this manually adding up all the hit % on items worn by the caster:
![image](https://github.com/user-attachments/assets/27d93406-bda0-4dcb-a50d-78f3a6902086)

## Version
Classic Era
ECS v3.3.5

**Comment by BreakBB** [comment]
Hey @retrobloodfang it looks indeed like ECS currently does calculate Suppression points in as well. That is not correct, as you already said because it only affects Affliction spells.

Overall ECS is a bit inconsistent about which talents to take into account and which not, because of the fact that some talents only effect certain spell schools.

**Comment by BreakBB** [comment]
For example for Mages we take "Elemental Precision" into account and for Priests we do the same with "Shadow Focus". It is a mess 🙈

**Comment by retrobloodfang** [comment]
@BreakBB this issue isn't resolved so I wouldn't call this closed, no? It would help if you just multiple the warlock talents 2x. 5 out of 5 points means 10% extra hit for affliction. Just like 1 point in elemental precision gives 2% hit for a total of 6% when you 3/3 the talent. 

And for priests, this is also 2% per point and a good priest should know it's just shadow spells that gain the hit. 

Good warlocks and priests should know their extra hit only counts for 1 school of magic, I don't think that's an issue. The core issue lies in the wrong calculation for hit for Warlocks (I haven't checked if this is the case for priest as well), you assume 1 talent point = 1% extra hit when it's actually 2%.

Wouldn't it be fixed if you changed this? Or did you change this already?

**Comment by BreakBB** [comment]
Hey @retrobloodfang  

In 7dc6e81287c4f07f1985d4a8381372dede31796a I changed it, so that the Suppression talent is not taken into account at all for non WotLK clients anymore.

That resolved the issue about 1% vs. 2% which was present before and also aligns with the screenshot from 60 upgrades you posted.
