### ISSUE TITLE
MP5 buffs and consumbales are not tracked

### ISSUE THREAD

**Issue by f90** [BreakBB/ExtendedCharacterStats#41]
## Bug description
For mage, the stat "MP5 (Casting)" does not take into account whether mage armor is currently active on the player.

## How to replicate/proof
1. Be a mage, let's say with arcane meditation skilled (15% manareg continues while casting)
2. Cast mage armor (gives 30% extra manareg while casting)
3. Check MP5 stats. MP5 (Casting) should be = (MP5(Spirit) * 0.45) + MP5 from Items. In my case, it's 140*0.45+13 = 76. However, the addon shows me 34, which is what you get if you use 0.15 as multiplier instead. So ECS ignores mage armor at the moment.

## Version
2.4.4

**Comment by BreakBB** [comment]
Oh wow, that is strange. I am calling the Blizzard server for those values and they should include the Mage Armor value. Well need to handle it separate then, but shouldn't be hard to implement. The next version will fix this.

Thanks for your report :pray:

**Comment by f90** [comment]
You probably mean the Blizzard function ``GetManaRegen()``? I tested it myself and it seems very buggy. Can't really trust those values, for example it gives 0 when within the 5s rule, even with arcane meditation. But it seems like the code accounts for some of that weird behaviour already.

But yeah, I think the only thing to add would be to check for mage armor buff being active at the moment, and depending on that change the multiplier.

**Comment by BreakBB** [comment]
Yeah MP5 by items is calculated different. And you're also right that ECS already skippes the 5 sec rule for updating because of that weird behaviour.

Changing MP5 gear should work though, because ECS iterates the gear and sums up the MP5 values :thinking:

MP5 buffs in general aren't reflected atm I'm afraid. Other users reported neither Mageblood Potion nor Nightfin Soup is added to the values due to GetManaRegen doesn't return changes with those buffs active.

But as I said should be easy to add since changes are already checked when the player receives/loses a buff/debuff.

**Comment by f90** [comment]
Maybe add another stat MP5 (Buffs) that tries to count all those buffs/debuffs currently on the character, which then gets added to the MP5 (Casting) stat at the end? Doesn't make sense to include it into MP5 (Items) stat due to the name of the stat.

**Comment by BreakBB** [comment]
@f90 I planned to add a new section for the buffs/consumables MP5 values, like you suggested.

**Comment by BreakBB** [comment]
Things to include:

- Mageblood Potion
- Nightfin Soup
- Warchief's Blessing

**Comment by helvexis** [comment]
With P5 coming Mana oils will probably have to go into that as well
